# config file version
apiVersion: 1

# adapted from https://grafana.com/docs/grafana/latest/datasources/postgres/#provision-the-data-source
datasources:
  - name: AutoPostgreSQL
    type: postgres
    url: to-be-set-via-env:5432
    user: to-be-set-via-env
    secureJsonData:
      password: 'to-be-set-via-env'
    jsonData:
      database: to-be-set-via-env
      sslmode: 'require' # disable/require/verify-ca/verify-full
      maxOpenConns: 50 # Grafana v5.4+
      maxIdleConns: 50 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1200
      timescaledb: false
